import Navbar2 from '@/Component/Navbar2/Navbar2'
import React from 'react'
import Hero from './Hero/Hero'
import Card from './Card/Card'
import Footer from '@/Component/Footer/Footer'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: "Connect-VogueAura , For more to Know",
  description: "Generated by Owais Khiljee",
};


const page = () => {
  return (
    <div>
        <Navbar2 />
        <Hero />
        <Card/>
        <Footer backgroundColor='#FFFFFF' />
    </div>
  )
}

export default page


