import React from 'react'
import Hero from './Hero/Hero'
import Pricing from '@/Component/FrequentComponent/Pricing'
import Footer from '@/Component/Footer/Footer'
import FAQSection from './FAQSection/FAQSection'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: "Pricing, To Join VogueAura",
  description: "Generated by Owais Khiljee",
};

const page = () => {
  return (
    <div>
        <Hero />
        <FAQSection />
        <Pricing />
        <Footer  backgroundColor='#FFFFFF'/>
    </div>
  )
}

export default page


