import { client } from '@/sanity/lib/client';
import Hero from '@/app/ProductPage/Hero/Hero';
import DescriptionPage from '@/app/ProductPage/DescriptionPage/DescriptionPage';
import React from 'react';
import Footer from '@/Component/Footer/Footer';
import Brandlogos from '@/Component/FrequentComponent/Brandlogos';
import { Metadata } from 'next';
import ReviewSection from '@/app/ProductPage/ReviewSection/ReviewSection';

export const metadata: Metadata = {
  title: "About Product ",
  description: "Generated by Owais Khiljee",
};

interface ProductPageProps {
  params: {
    id: string;
  };
}

const ProductPage = async ({ params }: ProductPageProps) => {
  try {
    const data = await client.fetch(
      `*[_type == "apiproduct" && _id == $id][0] {
        _id ,
              Title , 
              Description , 
              BulletPoints , 
              DiscountedPrice ,
              OriginalPrice,
              "MainImage": MainImage.asset->url ,
              "Images": Images[].asset->url ,
              "DescriptionImages": DescriptionImages.asset->url ,
              Category,
              Tags,
              Rating,
              Reviews,
              Stock,
              Colors,
      }`,
      { id: params.id }
    );

    if (!data) {
      throw new Error('Product not found');
    }

    return (<><Hero
      {...data} /><DescriptionPage Description={data.Description} DescriptionImages={data.DescriptionImages} Reviews={data.Reviews} />
      <ReviewSection   productId={data._id}/>

      <Brandlogos />
      <Footer  backgroundColor='#FFFFFF'/>
      </>
    )
  } catch (error) {
    console.error('Error fetching product:', error);
    return (
      <div>
        Product not Found
      </div>
      
    )
  }
};

export default ProductPage;
