import { client } from '@/sanity/lib/client';
import Hero from '@/app/ProductPage/Hero/Hero';
import DescriptionPage from '@/app/ProductPage/DescriptionPage/DescriptionPage';
import React from 'react';
import BestsellerProduct from '@/app/ProductPage/BestsellerProduct/BestsellerProduct';
import Footer from '@/Component/Footer/Footer';
import Brandlogos from '@/Component/FrequentComponent/Brandlogos';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "About Product ",
  description: "Generated by Owais Khiljee",
};

interface ProductPageProps {
  params: {
    id: string;
  };
}

const ProductPage = async ({ params }: ProductPageProps) => {
  try {
    const data = await client.fetch(
      `*[_type == "product" && _id == $id][0] {
        _id,
        title,
        "imageUrl": productImage.asset->url,
        price,
        description
      }`,
      { id: params.id }
    );

    if (!data) {
      throw new Error('Product not found');
    }

    return (<><Hero
      {...data} /><DescriptionPage description={data.description} imageUrl={data.imageUrl} />
      <BestsellerProduct />
      <Brandlogos />
      <Footer  backgroundColor='#FFFFFF'/>
      </>
    )
  } catch (error) {
    console.error('Error fetching product:', error);
    return (
      <div>
        Product not Found
      </div>
      
    )
  }
};

export default ProductPage;
